name: Obtener Secreto desde Azure Key Vault

on:
  workflow_dispatch:  # Permitir desencadenar manualmente
    inputs:
      secret_name:
        description: 'Nombre del secreto en Azure Key Vault'
        required: true

jobs:
  control-container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Discord Token from Azure Key Vault
        id: get-secret
        run: |
          SECRET_VALUE=$(az keyvault secret show --name ${{ github.event.inputs.secret_name }} --vault-name radio-keyVault --query value -o tsv)
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV

      - name: Control Azure Container Instance
        run: |
          az container ${{ github.event.action }} --resource-group ${{ secrets.RESOURCE_GROUP }} --name discord-bot --environment-variables SECRET_VALUE=${{ env.SECRET_VALUE }}
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}